INSERT INTO public.roles (id, role) VALUES (444, 'USER');
INSERT INTO public.roles (id, role) VALUES (555, 'ADMIN');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1011, '2017-05-11 21:00:00', '2017-05-11 10:00:00', 10019, 194, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (731, 1, 1, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (732, 1, 2, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (733, 1, 3, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (734, 1, 4, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (735, 1, 5, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (736, 1, 6, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (737, 1, 7, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (738, 1, 8, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (739, 1, 9, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (740, 1, 10, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (741, 1, 11, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (742, 1, 12, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (743, 1, 13, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (744, 1, 14, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (745, 1, 15, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (746, 1, 16, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (747, 1, 17, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (748, 1, 18, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (749, 1, 19, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (750, 1, 20, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (751, 2, 1, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (752, 2, 2, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (753, 2, 3, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (754, 2, 4, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (755, 2, 5, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (756, 2, 6, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (757, 2, 7, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (758, 2, 8, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (759, 2, 9, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (760, 2, 10, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (761, 2, 11, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (762, 2, 12, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (763, 2, 13, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (764, 2, 14, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (765, 2, 15, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (766, 2, 16, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (767, 2, 17, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (768, 2, 18, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (769, 2, 19, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (770, 2, 20, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (771, 3, 1, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (772, 3, 2, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (773, 3, 3, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (774, 3, 4, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (775, 3, 5, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (776, 3, 6, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (777, 3, 7, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (778, 3, 8, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (779, 3, 9, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (780, 3, 10, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (781, 3, 11, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (782, 3, 12, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (783, 3, 13, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (784, 3, 14, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (785, 3, 15, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (786, 3, 16, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (787, 3, 17, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (788, 3, 18, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (789, 3, 19, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (790, 3, 20, 'F01');
INSERT INTO public.stations (id, station_name) VALUES (10000, 'Aarau');
INSERT INTO public.stations (id, station_name) VALUES (10001, 'Aarburg');
INSERT INTO public.stations (id, station_name) VALUES (10002, 'Baden');
INSERT INTO public.stations (id, station_name) VALUES (10003, 'Bremgarten');
INSERT INTO public.stations (id, station_name) VALUES (10004, 'Brugg');
INSERT INTO public.stations (id, station_name) VALUES (10005, 'Kaiserstuhl');
INSERT INTO public.stations (id, station_name) VALUES (10006, 'Klingnau');
INSERT INTO public.stations (id, station_name) VALUES (10007, 'Laufenburg');
INSERT INTO public.stations (id, station_name) VALUES (10008, 'Lenzburg');
INSERT INTO public.stations (id, station_name) VALUES (10009, 'Mellingen');
INSERT INTO public.stations (id, station_name) VALUES (10010, 'Oftringen');
INSERT INTO public.stations (id, station_name) VALUES (10011, 'Rheinfelden');
INSERT INTO public.stations (id, station_name) VALUES (10012, 'Spreitenbach');
INSERT INTO public.stations (id, station_name) VALUES (10013, 'Wettingen');
INSERT INTO public.stations (id, station_name) VALUES (10014, 'Wohlen');
INSERT INTO public.stations (id, station_name) VALUES (10015, 'Zofingen');
INSERT INTO public.stations (id, station_name) VALUES (10016, 'Zurzach');
INSERT INTO public.stations (id, station_name) VALUES (10017, 'Herisau');
INSERT INTO public.stations (id, station_name) VALUES (10018, 'Appenzell');
INSERT INTO public.stations (id, station_name) VALUES (10019, 'Basel');
INSERT INTO public.stations (id, station_name) VALUES (10020, 'Riehen');
INSERT INTO public.stations (id, station_name) VALUES (10021, 'Allschwil');
INSERT INTO public.stations (id, station_name) VALUES (10022, 'Binningen');
INSERT INTO public.stations (id, station_name) VALUES (10023, 'Birsfelden');
INSERT INTO public.stations (id, station_name) VALUES (10024, 'Laufen');
INSERT INTO public.stations (id, station_name) VALUES (10025, 'Liestal');
INSERT INTO public.stations (id, station_name) VALUES (10026, 'Munchenstein');
INSERT INTO public.stations (id, station_name) VALUES (10027, 'Muttenz');
INSERT INTO public.stations (id, station_name) VALUES (10028, 'Pratteln');
INSERT INTO public.stations (id, station_name) VALUES (10029, 'Reinach');
INSERT INTO public.stations (id, station_name) VALUES (10030, 'Waldenburg');
INSERT INTO public.stations (id, station_name) VALUES (10031, 'Aarberg');
INSERT INTO public.stations (id, station_name) VALUES (10032, 'Bern');
INSERT INTO public.stations (id, station_name) VALUES (10033, 'Biel/Bienne');
INSERT INTO public.stations (id, station_name) VALUES (10034, 'Burgdorf');
INSERT INTO public.stations (id, station_name) VALUES (10035, 'Erlach');
INSERT INTO public.stations (id, station_name) VALUES (10036, 'Huttwil');
INSERT INTO public.stations (id, station_name) VALUES (10037, 'Ittigen');
INSERT INTO public.stations (id, station_name) VALUES (10038, 'Koniz');
INSERT INTO public.stations (id, station_name) VALUES (10039, 'La Neuveville');
INSERT INTO public.stations (id, station_name) VALUES (10040, 'Langenthal');
INSERT INTO public.stations (id, station_name) VALUES (10041, 'Laupen');
INSERT INTO public.stations (id, station_name) VALUES (10042, 'Lyss');
INSERT INTO public.stations (id, station_name) VALUES (10043, 'Moutier');
INSERT INTO public.stations (id, station_name) VALUES (10044, 'MÃ¼nsingen');
INSERT INTO public.stations (id, station_name) VALUES (10045, 'Muri');
INSERT INTO public.stations (id, station_name) VALUES (10046, 'Nidau');
INSERT INTO public.stations (id, station_name) VALUES (10047, 'Ostermundigen');
INSERT INTO public.stations (id, station_name) VALUES (10048, 'Spiez');
INSERT INTO public.stations (id, station_name) VALUES (10049, 'Steffisburg');
INSERT INTO public.stations (id, station_name) VALUES (10050, 'Thun');
INSERT INTO public.stations (id, station_name) VALUES (10051, 'Unterseen');
INSERT INTO public.stations (id, station_name) VALUES (10052, 'Wangen an der Aare');
INSERT INTO public.stations (id, station_name) VALUES (10053, 'Wiedlisbach');
INSERT INTO public.stations (id, station_name) VALUES (10054, 'Worb');
INSERT INTO public.stations (id, station_name) VALUES (10055, 'Bulle');
INSERT INTO public.stations (id, station_name) VALUES (10056, 'Chatel-Saint-Denis');
INSERT INTO public.stations (id, station_name) VALUES (10057, 'Estavayer-le-Lac');
INSERT INTO public.stations (id, station_name) VALUES (10058, 'Fribourg');
INSERT INTO public.stations (id, station_name) VALUES (10059, 'Gruyeres');
INSERT INTO public.stations (id, station_name) VALUES (10060, 'La Tour-de-Treme');
INSERT INTO public.stations (id, station_name) VALUES (10061, 'Murten');
INSERT INTO public.stations (id, station_name) VALUES (10062, 'Romont');
INSERT INTO public.stations (id, station_name) VALUES (10063, 'Rue');
INSERT INTO public.stations (id, station_name) VALUES (10064, 'Carouge');
INSERT INTO public.stations (id, station_name) VALUES (10065, 'Geneva');
INSERT INTO public.stations (id, station_name) VALUES (10066, 'Hermance');
INSERT INTO public.stations (id, station_name) VALUES (10067, 'Lancy');
INSERT INTO public.stations (id, station_name) VALUES (10068, 'Meyrin');
INSERT INTO public.stations (id, station_name) VALUES (10069, 'Onex');
INSERT INTO public.stations (id, station_name) VALUES (10070, 'Thonex');
INSERT INTO public.stations (id, station_name) VALUES (10071, 'Vernier');
INSERT INTO public.stations (id, station_name) VALUES (10072, 'Versoix');
INSERT INTO public.stations (id, station_name) VALUES (10073, 'Glarus');
INSERT INTO public.stations (id, station_name) VALUES (10074, 'Chur');
INSERT INTO public.stations (id, station_name) VALUES (10075, 'Davos');
INSERT INTO public.stations (id, station_name) VALUES (10076, 'Ilanz');
INSERT INTO public.stations (id, station_name) VALUES (10077, 'Maienfeld');
INSERT INTO public.stations (id, station_name) VALUES (10078, 'Splugen');
INSERT INTO public.stations (id, station_name) VALUES (10079, 'Thusis');
INSERT INTO public.stations (id, station_name) VALUES (10080, 'Delemont');
INSERT INTO public.stations (id, station_name) VALUES (10081, 'Porrentruy');
INSERT INTO public.stations (id, station_name) VALUES (10082, 'Saint-Ursanne');
INSERT INTO public.stations (id, station_name) VALUES (10083, 'Beromunster');
INSERT INTO public.stations (id, station_name) VALUES (10084, 'Ebikon');
INSERT INTO public.stations (id, station_name) VALUES (10085, 'Emmen');
INSERT INTO public.stations (id, station_name) VALUES (10086, 'Horw');
INSERT INTO public.stations (id, station_name) VALUES (10087, 'Kriens');
INSERT INTO public.stations (id, station_name) VALUES (10088, 'Lucerne');
INSERT INTO public.stations (id, station_name) VALUES (10089, 'Sempach');
INSERT INTO public.stations (id, station_name) VALUES (10090, 'Sursee');
INSERT INTO public.stations (id, station_name) VALUES (10091, 'Willisau');
INSERT INTO public.stations (id, station_name) VALUES (10092, 'Boudry');
INSERT INTO public.stations (id, station_name) VALUES (10093, 'La Chaux-de-Fonds');
INSERT INTO public.stations (id, station_name) VALUES (10094, 'Le Landeron');
INSERT INTO public.stations (id, station_name) VALUES (10095, 'Le Locle');
INSERT INTO public.stations (id, station_name) VALUES (10096, 'Neuchatel');
INSERT INTO public.stations (id, station_name) VALUES (10097, 'Valangin');
INSERT INTO public.stations (id, station_name) VALUES (10098, 'Stans');
INSERT INTO public.stations (id, station_name) VALUES (10099, 'Sarnen');
INSERT INTO public.stations (id, station_name) VALUES (10100, 'Neuhausen');
INSERT INTO public.stations (id, station_name) VALUES (10101, 'Neunkirch');
INSERT INTO public.stations (id, station_name) VALUES (10102, 'Schaffhausen');
INSERT INTO public.stations (id, station_name) VALUES (10103, 'Stein am Rhein');
INSERT INTO public.stations (id, station_name) VALUES (10104, 'Einsiedeln');
INSERT INTO public.stations (id, station_name) VALUES (10105, 'Freienbach');
INSERT INTO public.stations (id, station_name) VALUES (10106, 'Kussnacht');
INSERT INTO public.stations (id, station_name) VALUES (10107, 'Lachen');
INSERT INTO public.stations (id, station_name) VALUES (10108, 'Schwyz');
INSERT INTO public.stations (id, station_name) VALUES (10109, 'Grenchen');
INSERT INTO public.stations (id, station_name) VALUES (10110, 'Olten');
INSERT INTO public.stations (id, station_name) VALUES (10111, 'Solothurn');
INSERT INTO public.stations (id, station_name) VALUES (10112, 'Altstatten');
INSERT INTO public.stations (id, station_name) VALUES (10113, 'Buchs');
INSERT INTO public.stations (id, station_name) VALUES (10114, 'Gossau');
INSERT INTO public.stations (id, station_name) VALUES (10115, 'Lichtensteig');
INSERT INTO public.stations (id, station_name) VALUES (10116, 'Rapperswil-Jona');
INSERT INTO public.stations (id, station_name) VALUES (10117, 'Rheineck');
INSERT INTO public.stations (id, station_name) VALUES (10118, 'Rorschach');
INSERT INTO public.stations (id, station_name) VALUES (10119, 'St. Gallen');
INSERT INTO public.stations (id, station_name) VALUES (10120, 'Sargans');
INSERT INTO public.stations (id, station_name) VALUES (10121, 'Uznach');
INSERT INTO public.stations (id, station_name) VALUES (10122, 'Uzwil');
INSERT INTO public.stations (id, station_name) VALUES (10123, 'Walenstadt');
INSERT INTO public.stations (id, station_name) VALUES (10124, 'Werdenberg');
INSERT INTO public.stations (id, station_name) VALUES (10125, 'Wil');
INSERT INTO public.stations (id, station_name) VALUES (10126, 'Amriswil');
INSERT INTO public.stations (id, station_name) VALUES (10127, 'Arbon');
INSERT INTO public.stations (id, station_name) VALUES (10128, 'Bischofszell');
INSERT INTO public.stations (id, station_name) VALUES (10129, 'Diessenhofen');
INSERT INTO public.stations (id, station_name) VALUES (10130, 'Frauenfeld');
INSERT INTO public.stations (id, station_name) VALUES (10131, 'Kreuzlingen');
INSERT INTO public.stations (id, station_name) VALUES (10132, 'Steckborn');
INSERT INTO public.stations (id, station_name) VALUES (10133, 'Agno');
INSERT INTO public.stations (id, station_name) VALUES (10134, 'Ascona');
INSERT INTO public.stations (id, station_name) VALUES (10135, 'Bellinzona');
INSERT INTO public.stations (id, station_name) VALUES (10136, 'Biasca');
INSERT INTO public.stations (id, station_name) VALUES (10137, 'Croglio');
INSERT INTO public.stations (id, station_name) VALUES (10138, 'Gordola');
INSERT INTO public.stations (id, station_name) VALUES (10139, 'Locarno');
INSERT INTO public.stations (id, station_name) VALUES (10140, 'Losone');
INSERT INTO public.stations (id, station_name) VALUES (10141, 'Lugano');
INSERT INTO public.stations (id, station_name) VALUES (10142, 'Mendrisio');
INSERT INTO public.stations (id, station_name) VALUES (10143, 'Morcote');
INSERT INTO public.stations (id, station_name) VALUES (10144, 'Riva San Vitale');
INSERT INTO public.stations (id, station_name) VALUES (10145, 'Sala');
INSERT INTO public.stations (id, station_name) VALUES (10146, 'Altdorf');
INSERT INTO public.stations (id, station_name) VALUES (10147, 'Bourg-Saint-Pierre');
INSERT INTO public.stations (id, station_name) VALUES (10148, 'Brig');
INSERT INTO public.stations (id, station_name) VALUES (10149, 'Conthey');
INSERT INTO public.stations (id, station_name) VALUES (10150, 'Leuk');
INSERT INTO public.stations (id, station_name) VALUES (10151, 'Martigny');
INSERT INTO public.stations (id, station_name) VALUES (10152, 'Monthey');
INSERT INTO public.stations (id, station_name) VALUES (10153, 'Orsieres');
INSERT INTO public.stations (id, station_name) VALUES (10154, 'Saillon');
INSERT INTO public.stations (id, station_name) VALUES (10155, 'Saint-Maurice');
INSERT INTO public.stations (id, station_name) VALUES (10156, 'Sembrancher');
INSERT INTO public.stations (id, station_name) VALUES (10157, 'Sierre');
INSERT INTO public.stations (id, station_name) VALUES (10158, 'Sion');
INSERT INTO public.stations (id, station_name) VALUES (10159, 'Visp');
INSERT INTO public.stations (id, station_name) VALUES (10160, 'Aigle');
INSERT INTO public.stations (id, station_name) VALUES (10161, 'Aubonne');
INSERT INTO public.stations (id, station_name) VALUES (10162, 'Avenches');
INSERT INTO public.stations (id, station_name) VALUES (10163, 'Coppet');
INSERT INTO public.stations (id, station_name) VALUES (10164, 'Cossonay');
INSERT INTO public.stations (id, station_name) VALUES (10165, 'Cudrefin');
INSERT INTO public.stations (id, station_name) VALUES (10166, 'Cully');
INSERT INTO public.stations (id, station_name) VALUES (10167, 'Echallens');
INSERT INTO public.stations (id, station_name) VALUES (10168, 'Gland');
INSERT INTO public.stations (id, station_name) VALUES (10169, 'Grandcour');
INSERT INTO public.stations (id, station_name) VALUES (10170, 'Grandson');
INSERT INTO public.stations (id, station_name) VALUES (10171, 'La Sarraz');
INSERT INTO public.stations (id, station_name) VALUES (10172, 'La Tour-de-Peilz');
INSERT INTO public.stations (id, station_name) VALUES (10173, 'Les Clees');
INSERT INTO public.stations (id, station_name) VALUES (10174, 'Lausanne');
INSERT INTO public.stations (id, station_name) VALUES (10175, 'Lutry');
INSERT INTO public.stations (id, station_name) VALUES (10176, 'Montreux');
INSERT INTO public.stations (id, station_name) VALUES (10177, 'Morges');
INSERT INTO public.stations (id, station_name) VALUES (10178, 'Moudon');
INSERT INTO public.stations (id, station_name) VALUES (10179, 'Nyon');
INSERT INTO public.stations (id, station_name) VALUES (10180, 'Orbe');
INSERT INTO public.stations (id, station_name) VALUES (10181, 'Payerne');
INSERT INTO public.stations (id, station_name) VALUES (10182, 'Prilly');
INSERT INTO public.stations (id, station_name) VALUES (10183, 'Pully');
INSERT INTO public.stations (id, station_name) VALUES (10184, 'Renens');
INSERT INTO public.stations (id, station_name) VALUES (10185, 'Rolle');
INSERT INTO public.stations (id, station_name) VALUES (10186, 'Romainmotier');
INSERT INTO public.stations (id, station_name) VALUES (10187, 'Saint-Prex');
INSERT INTO public.stations (id, station_name) VALUES (10188, 'Vevey');
INSERT INTO public.stations (id, station_name) VALUES (10189, 'Villeneuve');
INSERT INTO public.stations (id, station_name) VALUES (10190, 'Yverdon-les-Bains');
INSERT INTO public.stations (id, station_name) VALUES (10191, 'Baar');
INSERT INTO public.stations (id, station_name) VALUES (10192, 'Cham');
INSERT INTO public.stations (id, station_name) VALUES (10193, 'Zug');
INSERT INTO public.stations (id, station_name) VALUES (10194, 'Adliswil');
INSERT INTO public.stations (id, station_name) VALUES (10195, 'Affoltern am Albis');
INSERT INTO public.stations (id, station_name) VALUES (10196, 'Bulach');
INSERT INTO public.stations (id, station_name) VALUES (10197, 'Dietikon');
INSERT INTO public.stations (id, station_name) VALUES (10198, 'Dubendorf');
INSERT INTO public.stations (id, station_name) VALUES (10199, 'Eglisau');
INSERT INTO public.stations (id, station_name) VALUES (10200, 'Elgg');
INSERT INTO public.stations (id, station_name) VALUES (10201, 'Greifensee');
INSERT INTO public.stations (id, station_name) VALUES (10202, 'Gruningen');
INSERT INTO public.stations (id, station_name) VALUES (10203, 'Horgen');
INSERT INTO public.stations (id, station_name) VALUES (10204, 'Illnau-Effretikon');
INSERT INTO public.stations (id, station_name) VALUES (10205, 'Kloten');
INSERT INTO public.stations (id, station_name) VALUES (10206, 'Kusnacht');
INSERT INTO public.stations (id, station_name) VALUES (10207, 'Meilen');
INSERT INTO public.stations (id, station_name) VALUES (10208, 'Opfikon');
INSERT INTO public.stations (id, station_name) VALUES (10209, 'Regensberg');
INSERT INTO public.stations (id, station_name) VALUES (10210, 'Regensdorf');
INSERT INTO public.stations (id, station_name) VALUES (10211, 'Rheinau');
INSERT INTO public.stations (id, station_name) VALUES (10212, 'Richterswil');
INSERT INTO public.stations (id, station_name) VALUES (10213, 'Ruti');
INSERT INTO public.stations (id, station_name) VALUES (10214, 'Schlieren');
INSERT INTO public.stations (id, station_name) VALUES (10215, 'Stafa');
INSERT INTO public.stations (id, station_name) VALUES (10216, 'Thalwil');
INSERT INTO public.stations (id, station_name) VALUES (10217, 'Uster');
INSERT INTO public.stations (id, station_name) VALUES (10218, 'Volketswil');
INSERT INTO public.stations (id, station_name) VALUES (10219, 'Wadenswil');
INSERT INTO public.stations (id, station_name) VALUES (10220, 'Wallisellen');
INSERT INTO public.stations (id, station_name) VALUES (10221, 'Wetzikon');
INSERT INTO public.stations (id, station_name) VALUES (10222, 'Winterthur');
INSERT INTO public.stations (id, station_name) VALUES (10223, 'Zollikon');
INSERT INTO public.stations (id, station_name) VALUES (10224, 'Mos');
INSERT INTO public.stations (id, station_name) VALUES (10225, 'Spb');
INSERT INTO public.stations (id, station_name) VALUES (130, 'Moscow');
INSERT INTO public.stations (id, station_name) VALUES (158, 'Yar');
INSERT INTO public.stations (id, station_name) VALUES (194, 'London');
INSERT INTO public.stations (id, station_name) VALUES (204, 'TEST_STATION');
INSERT INTO public.stations (id, station_name) VALUES (226, 'Luki');
INSERT INTO public.stations (id, station_name) VALUES (248, 'EEE');
INSERT INTO public.stations (id, station_name) VALUES (259, 'DD');
INSERT INTO public.stations (id, station_name) VALUES (361, 'Yaroslavl');
INSERT INTO public.stations (id, station_name) VALUES (362, 'Samara');
INSERT INTO public.stations (id, station_name) VALUES (405, 'TEST_STATION');
INSERT INTO public.stations (id, station_name) VALUES (407, 'TEST_STATION');
INSERT INTO public.tickets (id, user_id) VALUES (1012, 129);
INSERT INTO public.trains (id) VALUES ('TEST_TRAIN');
INSERT INTO public.trains (id) VALUES ('F01');
INSERT INTO public.trains (id) VALUES ('A303');
INSERT INTO public.trains (id) VALUES ('SE02');
INSERT INTO public.trains (id) VALUES ('TT30');
INSERT INTO public.trains (id) VALUES ('TEST');
INSERT INTO public.user_roles (user_id, role_id, ctid) VALUES (129, 444, '(0,2)');
INSERT INTO public.user_roles (user_id, role_id, ctid) VALUES (139, 555, '(0,3)');
INSERT INTO public.user_roles (user_id, role_id, ctid) VALUES (115, 444, '(0,4)');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (365, '2017-04-19', '1233hjkl@mail.ru', 'Rob', 'images/1491994236403.jpg', 'Tailor', '$2a$10$fLKk4MiBBm0Ey9oGxfB4ou/EXH.WNE1qhNAE.TmBsyq5iClB2Ekha');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (372, '1966-04-24', 'tdemonstration@mail.ru', 'Jeck', 'images/1492097780653.jpg', 'Tomson', '$2a$10$S19vOekrLGBjPEgkxZskauAa629ra/6vkXnzT4ces7OcNfK4Y5zE2');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (146, '2017-04-26', 'A@a', 'User', 'images/1491555005452.png', 'Bush', '$2a$10$PWcTngFnAQ1qrh9pugls4O7Ir0KmtuiuZVEs9goAQZd4/7qSDofum');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (727, NULL, 'TEST@TEST', NULL, NULL, NULL, 'TEST');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (139, '1995-08-31', 'Prendota@mail.ru', 'Alexander', './images/DEFAULT_IMAGE.png', 'Prendota', '$2a$10$0IKsw.1oLvNhpN00RtAZp.XzOdbweuRvSfUbAdgygZnW3YUnEr4wG');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (129, '2017-03-19', 'S@s', 'Joshe', 'images/1491429806827.jpg', 'Light', '$2a$10$8MDcF2y4BPoAWea5pSn/Fe0rENwMH5YW7.roczlFsfhCD0Jl5KYAC');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (212, '1955-04-25', 'Bob@bob', 'Bob', './images/DEFAULT_IMAGE.png', 'Kelso', '$2a$10$BCm.FxpuybK5Cdsa4FWXZeIoXGlWIt2//6gZfynkZDgIf5Ii4ccIm');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (115, NULL, 'testUser@text.com', NULL, NULL, NULL, 'pass');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (228, '1994-02-28', 'mepevekic@doanart.com', 'Tom', './images/DEFAULT_IMAGE.png', 'Jon', '$2a$10$lJj5WdsuB9OFYK4d24/a/uA8TTAxRlB0Com65EzAo3y6pkI2a6hOG');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (364, '1995-04-30', 'argv123@mail.ru', 'Tom', './images/DEFAULT_IMAGE.png', 'Pitd', '$2a$10$ZgZ9K.CfXP9DhNjLafKGO.88RUo.83YFzUVT/ZRg/Tp5e2zcZic9q');




