INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (365, '2017-04-19', '1233hjkl@mail.ru', 'Rob', 'images/1491994236403.jpg', 'Tailor', '$2a$10$fLKk4MiBBm0Ey9oGxfB4ou/EXH.WNE1qhNAE.TmBsyq5iClB2Ekha');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (372, '1966-04-24', 'tdemonstration@mail.ru', 'Jeck', 'images/1492097780653.jpg', 'Tomson', '$2a$10$S19vOekrLGBjPEgkxZskauAa629ra/6vkXnzT4ces7OcNfK4Y5zE2');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (139, '1995-08-31', 'Prendota@mail.ru', 'Alexander', './images/DEFAULT_IMAGE.png', 'Prendota', '$2a$10$0IKsw.1oLvNhpN00RtAZp.XzOdbweuRvSfUbAdgygZnW3YUnEr4wG');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (146, '2017-04-26', 'A@a', 'User', 'images/1491555005452.png', 'Bush', '$2a$10$PWcTngFnAQ1qrh9pugls4O7Ir0KmtuiuZVEs9goAQZd4/7qSDofum');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (212, '1955-04-25', 'Bob@bob', 'Bob', './images/DEFAULT_IMAGE.png', 'Kelso', '$2a$10$BCm.FxpuybK5Cdsa4FWXZeIoXGlWIt2//6gZfynkZDgIf5Ii4ccIm');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (115, NULL, 'testUser@text.com', NULL, NULL, NULL, 'pass');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (228, '1994-02-28', 'mepevekic@doanart.com', 'Tom', './images/DEFAULT_IMAGE.png', 'Jon', '$2a$10$lJj5WdsuB9OFYK4d24/a/uA8TTAxRlB0Com65EzAo3y6pkI2a6hOG');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (1174, NULL, 'TEST@TEST', NULL, NULL, NULL, 'TEST');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (364, '1995-04-30', 'argv123@mail.ru', 'Tom', './images/DEFAULT_IMAGE.png', 'Pitd', '$2a$10$ZgZ9K.CfXP9DhNjLafKGO.88RUo.83YFzUVT/ZRg/Tp5e2zcZic9q');
INSERT INTO public.users (id, birthday, email, firstname, image_path, lastname, password) VALUES (129, '2017-03-19', 'S@s', 'Joshe', 'images/1491429806827.jpg', 'Light', '$2a$10$8MDcF2y4BPoAWea5pSn/Fe0rENwMH5YW7.roczlFsfhCD0Jl5KYAC');
INSERT INTO public.roles (id, role) VALUES (444, 'USER');
INSERT INTO public.roles (id, role) VALUES (555, 'ADMIN');
INSERT INTO public.user_roles (user_id, role_id, ctid) VALUES (129, 444, '(0,2)');
INSERT INTO public.user_roles (user_id, role_id, ctid) VALUES (139, 555, '(0,3)');
INSERT INTO public.user_roles (user_id, role_id, ctid) VALUES (115, 444, '(0,4)');
INSERT INTO public.trains (id) VALUES ('F01');
INSERT INTO public.trains (id) VALUES ('A303');
INSERT INTO public.trains (id) VALUES ('SE02');
INSERT INTO public.trains (id) VALUES ('TT30');
INSERT INTO public.trains (id) VALUES ('B18');
INSERT INTO public.trains (id) VALUES ('O34');
INSERT INTO public.trains (id) VALUES ('TEST');
INSERT INTO public.trains (id) VALUES ('TEST_TRAIN');
INSERT INTO public.stations (id, station_name) VALUES (10000, 'Aarau');
INSERT INTO public.stations (id, station_name) VALUES (10001, 'Aarburg');
INSERT INTO public.stations (id, station_name) VALUES (10002, 'Baden');
INSERT INTO public.stations (id, station_name) VALUES (10003, 'Bremgarten');
INSERT INTO public.stations (id, station_name) VALUES (10004, 'Brugg');
INSERT INTO public.stations (id, station_name) VALUES (10005, 'Kaiserstuhl');
INSERT INTO public.stations (id, station_name) VALUES (10006, 'Klingnau');
INSERT INTO public.stations (id, station_name) VALUES (10007, 'Laufenburg');
INSERT INTO public.stations (id, station_name) VALUES (10008, 'Lenzburg');
INSERT INTO public.stations (id, station_name) VALUES (10009, 'Mellingen');
INSERT INTO public.stations (id, station_name) VALUES (10010, 'Oftringen');
INSERT INTO public.stations (id, station_name) VALUES (10011, 'Rheinfelden');
INSERT INTO public.stations (id, station_name) VALUES (10012, 'Spreitenbach');
INSERT INTO public.stations (id, station_name) VALUES (10013, 'Wettingen');
INSERT INTO public.stations (id, station_name) VALUES (10014, 'Wohlen');
INSERT INTO public.stations (id, station_name) VALUES (10015, 'Zofingen');
INSERT INTO public.stations (id, station_name) VALUES (10016, 'Zurzach');
INSERT INTO public.stations (id, station_name) VALUES (10017, 'Herisau');
INSERT INTO public.stations (id, station_name) VALUES (10018, 'Appenzell');
INSERT INTO public.stations (id, station_name) VALUES (10019, 'Basel');
INSERT INTO public.stations (id, station_name) VALUES (10020, 'Riehen');
INSERT INTO public.stations (id, station_name) VALUES (10021, 'Allschwil');
INSERT INTO public.stations (id, station_name) VALUES (10022, 'Binningen');
INSERT INTO public.stations (id, station_name) VALUES (10023, 'Birsfelden');
INSERT INTO public.stations (id, station_name) VALUES (10024, 'Laufen');
INSERT INTO public.stations (id, station_name) VALUES (10025, 'Liestal');
INSERT INTO public.stations (id, station_name) VALUES (10026, 'Munchenstein');
INSERT INTO public.stations (id, station_name) VALUES (10027, 'Muttenz');
INSERT INTO public.stations (id, station_name) VALUES (10028, 'Pratteln');
INSERT INTO public.stations (id, station_name) VALUES (10029, 'Reinach');
INSERT INTO public.stations (id, station_name) VALUES (10030, 'Waldenburg');
INSERT INTO public.stations (id, station_name) VALUES (10031, 'Aarberg');
INSERT INTO public.stations (id, station_name) VALUES (10032, 'Bern');
INSERT INTO public.stations (id, station_name) VALUES (10033, 'Biel/Bienne');
INSERT INTO public.stations (id, station_name) VALUES (10034, 'Burgdorf');
INSERT INTO public.stations (id, station_name) VALUES (10035, 'Erlach');
INSERT INTO public.stations (id, station_name) VALUES (10036, 'Huttwil');
INSERT INTO public.stations (id, station_name) VALUES (10037, 'Ittigen');
INSERT INTO public.stations (id, station_name) VALUES (10038, 'Koniz');
INSERT INTO public.stations (id, station_name) VALUES (10039, 'La Neuveville');
INSERT INTO public.stations (id, station_name) VALUES (10040, 'Langenthal');
INSERT INTO public.stations (id, station_name) VALUES (10041, 'Laupen');
INSERT INTO public.stations (id, station_name) VALUES (10042, 'Lyss');
INSERT INTO public.stations (id, station_name) VALUES (10043, 'Moutier');
INSERT INTO public.stations (id, station_name) VALUES (10044, 'MÃ¼nsingen');
INSERT INTO public.stations (id, station_name) VALUES (10045, 'Muri');
INSERT INTO public.stations (id, station_name) VALUES (10046, 'Nidau');
INSERT INTO public.stations (id, station_name) VALUES (10047, 'Ostermundigen');
INSERT INTO public.stations (id, station_name) VALUES (10048, 'Spiez');
INSERT INTO public.stations (id, station_name) VALUES (10049, 'Steffisburg');
INSERT INTO public.stations (id, station_name) VALUES (10050, 'Thun');
INSERT INTO public.stations (id, station_name) VALUES (10051, 'Unterseen');
INSERT INTO public.stations (id, station_name) VALUES (10052, 'Wangen an der Aare');
INSERT INTO public.stations (id, station_name) VALUES (10053, 'Wiedlisbach');
INSERT INTO public.stations (id, station_name) VALUES (10054, 'Worb');
INSERT INTO public.stations (id, station_name) VALUES (10055, 'Bulle');
INSERT INTO public.stations (id, station_name) VALUES (10056, 'Chatel-Saint-Denis');
INSERT INTO public.stations (id, station_name) VALUES (10057, 'Estavayer-le-Lac');
INSERT INTO public.stations (id, station_name) VALUES (10058, 'Fribourg');
INSERT INTO public.stations (id, station_name) VALUES (10059, 'Gruyeres');
INSERT INTO public.stations (id, station_name) VALUES (10060, 'La Tour-de-Treme');
INSERT INTO public.stations (id, station_name) VALUES (10061, 'Murten');
INSERT INTO public.stations (id, station_name) VALUES (10062, 'Romont');
INSERT INTO public.stations (id, station_name) VALUES (10063, 'Rue');
INSERT INTO public.stations (id, station_name) VALUES (10064, 'Carouge');
INSERT INTO public.stations (id, station_name) VALUES (10065, 'Geneva');
INSERT INTO public.stations (id, station_name) VALUES (10066, 'Hermance');
INSERT INTO public.stations (id, station_name) VALUES (10067, 'Lancy');
INSERT INTO public.stations (id, station_name) VALUES (10068, 'Meyrin');
INSERT INTO public.stations (id, station_name) VALUES (10069, 'Onex');
INSERT INTO public.stations (id, station_name) VALUES (10070, 'Thonex');
INSERT INTO public.stations (id, station_name) VALUES (10071, 'Vernier');
INSERT INTO public.stations (id, station_name) VALUES (10072, 'Versoix');
INSERT INTO public.stations (id, station_name) VALUES (10073, 'Glarus');
INSERT INTO public.stations (id, station_name) VALUES (10074, 'Chur');
INSERT INTO public.stations (id, station_name) VALUES (10075, 'Davos');
INSERT INTO public.stations (id, station_name) VALUES (10076, 'Ilanz');
INSERT INTO public.stations (id, station_name) VALUES (10077, 'Maienfeld');
INSERT INTO public.stations (id, station_name) VALUES (10078, 'Splugen');
INSERT INTO public.stations (id, station_name) VALUES (10079, 'Thusis');
INSERT INTO public.stations (id, station_name) VALUES (10080, 'Delemont');
INSERT INTO public.stations (id, station_name) VALUES (10081, 'Porrentruy');
INSERT INTO public.stations (id, station_name) VALUES (10082, 'Saint-Ursanne');
INSERT INTO public.stations (id, station_name) VALUES (10083, 'Beromunster');
INSERT INTO public.stations (id, station_name) VALUES (10084, 'Ebikon');
INSERT INTO public.stations (id, station_name) VALUES (10085, 'Emmen');
INSERT INTO public.stations (id, station_name) VALUES (10086, 'Horw');
INSERT INTO public.stations (id, station_name) VALUES (10087, 'Kriens');
INSERT INTO public.stations (id, station_name) VALUES (10088, 'Lucerne');
INSERT INTO public.stations (id, station_name) VALUES (10089, 'Sempach');
INSERT INTO public.stations (id, station_name) VALUES (10090, 'Sursee');
INSERT INTO public.stations (id, station_name) VALUES (10091, 'Willisau');
INSERT INTO public.stations (id, station_name) VALUES (10092, 'Boudry');
INSERT INTO public.stations (id, station_name) VALUES (10093, 'La Chaux-de-Fonds');
INSERT INTO public.stations (id, station_name) VALUES (10094, 'Le Landeron');
INSERT INTO public.stations (id, station_name) VALUES (10095, 'Le Locle');
INSERT INTO public.stations (id, station_name) VALUES (10096, 'Neuchatel');
INSERT INTO public.stations (id, station_name) VALUES (10097, 'Valangin');
INSERT INTO public.stations (id, station_name) VALUES (10098, 'Stans');
INSERT INTO public.stations (id, station_name) VALUES (10099, 'Sarnen');
INSERT INTO public.stations (id, station_name) VALUES (10100, 'Neuhausen');
INSERT INTO public.stations (id, station_name) VALUES (10101, 'Neunkirch');
INSERT INTO public.stations (id, station_name) VALUES (10102, 'Schaffhausen');
INSERT INTO public.stations (id, station_name) VALUES (10103, 'Stein am Rhein');
INSERT INTO public.stations (id, station_name) VALUES (10104, 'Einsiedeln');
INSERT INTO public.stations (id, station_name) VALUES (10105, 'Freienbach');
INSERT INTO public.stations (id, station_name) VALUES (10106, 'Kussnacht');
INSERT INTO public.stations (id, station_name) VALUES (10107, 'Lachen');
INSERT INTO public.stations (id, station_name) VALUES (10108, 'Schwyz');
INSERT INTO public.stations (id, station_name) VALUES (10109, 'Grenchen');
INSERT INTO public.stations (id, station_name) VALUES (10110, 'Olten');
INSERT INTO public.stations (id, station_name) VALUES (10111, 'Solothurn');
INSERT INTO public.stations (id, station_name) VALUES (10112, 'Altstatten');
INSERT INTO public.stations (id, station_name) VALUES (10113, 'Buchs');
INSERT INTO public.stations (id, station_name) VALUES (10114, 'Gossau');
INSERT INTO public.stations (id, station_name) VALUES (10115, 'Lichtensteig');
INSERT INTO public.stations (id, station_name) VALUES (10116, 'Rapperswil-Jona');
INSERT INTO public.stations (id, station_name) VALUES (10117, 'Rheineck');
INSERT INTO public.stations (id, station_name) VALUES (10118, 'Rorschach');
INSERT INTO public.stations (id, station_name) VALUES (10119, 'St. Gallen');
INSERT INTO public.stations (id, station_name) VALUES (10120, 'Sargans');
INSERT INTO public.stations (id, station_name) VALUES (10121, 'Uznach');
INSERT INTO public.stations (id, station_name) VALUES (10122, 'Uzwil');
INSERT INTO public.stations (id, station_name) VALUES (10123, 'Walenstadt');
INSERT INTO public.stations (id, station_name) VALUES (10124, 'Werdenberg');
INSERT INTO public.stations (id, station_name) VALUES (10125, 'Wil');
INSERT INTO public.stations (id, station_name) VALUES (10126, 'Amriswil');
INSERT INTO public.stations (id, station_name) VALUES (10127, 'Arbon');
INSERT INTO public.stations (id, station_name) VALUES (10128, 'Bischofszell');
INSERT INTO public.stations (id, station_name) VALUES (10129, 'Diessenhofen');
INSERT INTO public.stations (id, station_name) VALUES (10130, 'Frauenfeld');
INSERT INTO public.stations (id, station_name) VALUES (10131, 'Kreuzlingen');
INSERT INTO public.stations (id, station_name) VALUES (10132, 'Steckborn');
INSERT INTO public.stations (id, station_name) VALUES (10133, 'Agno');
INSERT INTO public.stations (id, station_name) VALUES (10134, 'Ascona');
INSERT INTO public.stations (id, station_name) VALUES (10135, 'Bellinzona');
INSERT INTO public.stations (id, station_name) VALUES (10136, 'Biasca');
INSERT INTO public.stations (id, station_name) VALUES (10137, 'Croglio');
INSERT INTO public.stations (id, station_name) VALUES (10138, 'Gordola');
INSERT INTO public.stations (id, station_name) VALUES (10139, 'Locarno');
INSERT INTO public.stations (id, station_name) VALUES (10140, 'Losone');
INSERT INTO public.stations (id, station_name) VALUES (10141, 'Lugano');
INSERT INTO public.stations (id, station_name) VALUES (10142, 'Mendrisio');
INSERT INTO public.stations (id, station_name) VALUES (10143, 'Morcote');
INSERT INTO public.stations (id, station_name) VALUES (10144, 'Riva San Vitale');
INSERT INTO public.stations (id, station_name) VALUES (10145, 'Sala');
INSERT INTO public.stations (id, station_name) VALUES (10146, 'Altdorf');
INSERT INTO public.stations (id, station_name) VALUES (10147, 'Bourg-Saint-Pierre');
INSERT INTO public.stations (id, station_name) VALUES (10148, 'Brig');
INSERT INTO public.stations (id, station_name) VALUES (10149, 'Conthey');
INSERT INTO public.stations (id, station_name) VALUES (10150, 'Leuk');
INSERT INTO public.stations (id, station_name) VALUES (10151, 'Martigny');
INSERT INTO public.stations (id, station_name) VALUES (10152, 'Monthey');
INSERT INTO public.stations (id, station_name) VALUES (10153, 'Orsieres');
INSERT INTO public.stations (id, station_name) VALUES (10154, 'Saillon');
INSERT INTO public.stations (id, station_name) VALUES (10155, 'Saint-Maurice');
INSERT INTO public.stations (id, station_name) VALUES (10156, 'Sembrancher');
INSERT INTO public.stations (id, station_name) VALUES (10157, 'Sierre');
INSERT INTO public.stations (id, station_name) VALUES (10158, 'Sion');
INSERT INTO public.stations (id, station_name) VALUES (10159, 'Visp');
INSERT INTO public.stations (id, station_name) VALUES (10160, 'Aigle');
INSERT INTO public.stations (id, station_name) VALUES (10161, 'Aubonne');
INSERT INTO public.stations (id, station_name) VALUES (10162, 'Avenches');
INSERT INTO public.stations (id, station_name) VALUES (10163, 'Coppet');
INSERT INTO public.stations (id, station_name) VALUES (10164, 'Cossonay');
INSERT INTO public.stations (id, station_name) VALUES (10165, 'Cudrefin');
INSERT INTO public.stations (id, station_name) VALUES (10166, 'Cully');
INSERT INTO public.stations (id, station_name) VALUES (10167, 'Echallens');
INSERT INTO public.stations (id, station_name) VALUES (10168, 'Gland');
INSERT INTO public.stations (id, station_name) VALUES (10169, 'Grandcour');
INSERT INTO public.stations (id, station_name) VALUES (10170, 'Grandson');
INSERT INTO public.stations (id, station_name) VALUES (10171, 'La Sarraz');
INSERT INTO public.stations (id, station_name) VALUES (10172, 'La Tour-de-Peilz');
INSERT INTO public.stations (id, station_name) VALUES (10173, 'Les Clees');
INSERT INTO public.stations (id, station_name) VALUES (10174, 'Lausanne');
INSERT INTO public.stations (id, station_name) VALUES (10175, 'Lutry');
INSERT INTO public.stations (id, station_name) VALUES (10176, 'Montreux');
INSERT INTO public.stations (id, station_name) VALUES (10177, 'Morges');
INSERT INTO public.stations (id, station_name) VALUES (10178, 'Moudon');
INSERT INTO public.stations (id, station_name) VALUES (10179, 'Nyon');
INSERT INTO public.stations (id, station_name) VALUES (10180, 'Orbe');
INSERT INTO public.stations (id, station_name) VALUES (10181, 'Payerne');
INSERT INTO public.stations (id, station_name) VALUES (10182, 'Prilly');
INSERT INTO public.stations (id, station_name) VALUES (10183, 'Pully');
INSERT INTO public.stations (id, station_name) VALUES (10184, 'Renens');
INSERT INTO public.stations (id, station_name) VALUES (10185, 'Rolle');
INSERT INTO public.stations (id, station_name) VALUES (10186, 'Romainmotier');
INSERT INTO public.stations (id, station_name) VALUES (10187, 'Saint-Prex');
INSERT INTO public.stations (id, station_name) VALUES (10188, 'Vevey');
INSERT INTO public.stations (id, station_name) VALUES (10189, 'Villeneuve');
INSERT INTO public.stations (id, station_name) VALUES (10190, 'Yverdon-les-Bains');
INSERT INTO public.stations (id, station_name) VALUES (10191, 'Baar');
INSERT INTO public.stations (id, station_name) VALUES (10192, 'Cham');
INSERT INTO public.stations (id, station_name) VALUES (10193, 'Zug');
INSERT INTO public.stations (id, station_name) VALUES (10194, 'Adliswil');
INSERT INTO public.stations (id, station_name) VALUES (10195, 'Affoltern am Albis');
INSERT INTO public.stations (id, station_name) VALUES (10196, 'Bulach');
INSERT INTO public.stations (id, station_name) VALUES (10197, 'Dietikon');
INSERT INTO public.stations (id, station_name) VALUES (10198, 'Dubendorf');
INSERT INTO public.stations (id, station_name) VALUES (10199, 'Eglisau');
INSERT INTO public.stations (id, station_name) VALUES (10200, 'Elgg');
INSERT INTO public.stations (id, station_name) VALUES (10201, 'Greifensee');
INSERT INTO public.stations (id, station_name) VALUES (10202, 'Gruningen');
INSERT INTO public.stations (id, station_name) VALUES (10203, 'Horgen');
INSERT INTO public.stations (id, station_name) VALUES (10204, 'Illnau-Effretikon');
INSERT INTO public.stations (id, station_name) VALUES (10205, 'Kloten');
INSERT INTO public.stations (id, station_name) VALUES (10206, 'Kusnacht');
INSERT INTO public.stations (id, station_name) VALUES (10207, 'Meilen');
INSERT INTO public.stations (id, station_name) VALUES (10208, 'Opfikon');
INSERT INTO public.stations (id, station_name) VALUES (10209, 'Regensberg');
INSERT INTO public.stations (id, station_name) VALUES (10210, 'Regensdorf');
INSERT INTO public.stations (id, station_name) VALUES (10211, 'Rheinau');
INSERT INTO public.stations (id, station_name) VALUES (10212, 'Richterswil');
INSERT INTO public.stations (id, station_name) VALUES (10213, 'Ruti');
INSERT INTO public.stations (id, station_name) VALUES (10214, 'Schlieren');
INSERT INTO public.stations (id, station_name) VALUES (10215, 'Stafa');
INSERT INTO public.stations (id, station_name) VALUES (10216, 'Thalwil');
INSERT INTO public.stations (id, station_name) VALUES (10217, 'Uster');
INSERT INTO public.stations (id, station_name) VALUES (10218, 'Volketswil');
INSERT INTO public.stations (id, station_name) VALUES (10219, 'Wadenswil');
INSERT INTO public.stations (id, station_name) VALUES (10220, 'Wallisellen');
INSERT INTO public.stations (id, station_name) VALUES (10221, 'Wetzikon');
INSERT INTO public.stations (id, station_name) VALUES (10222, 'Winterthur');
INSERT INTO public.stations (id, station_name) VALUES (10223, 'Zollikon');
INSERT INTO public.stations (id, station_name) VALUES (130, 'Moscow');
INSERT INTO public.stations (id, station_name) VALUES (194, 'London');
INSERT INTO public.stations (id, station_name) VALUES (204, 'TEST_STATION');
INSERT INTO public.stations (id, station_name) VALUES (226, 'Luki');
INSERT INTO public.stations (id, station_name) VALUES (361, 'Yaroslavl');
INSERT INTO public.stations (id, station_name) VALUES (362, 'Samara');
INSERT INTO public.stations (id, station_name) VALUES (405, 'TEST_STATION');
INSERT INTO public.stations (id, station_name) VALUES (407, 'TEST_STATION');
INSERT INTO public.stations (id, station_name) VALUES (1014, 'Saint-Petersburg');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (731, 1, 1, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (732, 1, 2, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (733, 1, 3, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (734, 1, 4, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (735, 1, 5, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (736, 1, 6, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (737, 1, 7, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (738, 1, 8, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (739, 1, 9, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (740, 1, 10, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (741, 1, 11, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (742, 1, 12, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (743, 1, 13, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (744, 1, 14, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (745, 1, 15, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (746, 1, 16, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (747, 1, 17, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (748, 1, 18, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (749, 1, 19, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (750, 1, 20, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (751, 2, 1, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (752, 2, 2, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (753, 2, 3, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (754, 2, 4, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (755, 2, 5, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (756, 2, 6, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (757, 2, 7, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (758, 2, 8, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (759, 2, 9, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (760, 2, 10, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (761, 2, 11, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (762, 2, 12, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (763, 2, 13, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (764, 2, 14, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (765, 2, 15, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (766, 2, 16, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (767, 2, 17, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (768, 2, 18, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (769, 2, 19, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (770, 2, 20, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (771, 3, 1, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (772, 3, 2, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (773, 3, 3, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (774, 3, 4, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (775, 3, 5, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (776, 3, 6, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (777, 3, 7, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (778, 3, 8, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (779, 3, 9, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (780, 3, 10, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (781, 3, 11, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (782, 3, 12, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (783, 3, 13, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (784, 3, 14, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (785, 3, 15, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (786, 3, 16, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (787, 3, 17, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (788, 3, 18, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (789, 3, 19, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (790, 3, 20, 'F01');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (831, 1, 1, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (832, 1, 2, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (833, 1, 3, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (834, 1, 4, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (835, 1, 5, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (836, 1, 6, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (837, 1, 7, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (838, 1, 8, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (839, 1, 9, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (840, 1, 10, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (841, 1, 11, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (842, 1, 12, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (843, 1, 13, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (844, 1, 14, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (845, 1, 15, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (846, 1, 16, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (847, 1, 17, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (848, 1, 18, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (849, 1, 19, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (850, 1, 20, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (851, 2, 1, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (852, 2, 2, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (853, 2, 3, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (854, 2, 4, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (855, 2, 5, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (856, 2, 6, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (857, 2, 7, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (858, 2, 8, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (859, 2, 9, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (860, 2, 10, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (861, 2, 11, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (862, 2, 12, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (863, 2, 13, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (864, 2, 14, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (865, 2, 15, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (866, 2, 16, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (867, 2, 17, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (868, 2, 18, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (869, 2, 19, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (870, 2, 20, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (871, 3, 1, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (872, 3, 2, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (873, 3, 3, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (874, 3, 4, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (875, 3, 5, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (876, 3, 6, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (877, 3, 7, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (878, 3, 8, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (879, 3, 9, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (880, 3, 10, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (881, 3, 11, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (882, 3, 12, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (883, 3, 13, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (884, 3, 14, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (885, 3, 15, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (886, 3, 16, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (887, 3, 17, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (888, 3, 18, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (889, 3, 19, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (890, 3, 20, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (891, 4, 1, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (892, 4, 2, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (893, 4, 3, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (894, 4, 4, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (895, 4, 5, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (896, 4, 6, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (897, 4, 7, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (898, 4, 8, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (899, 4, 9, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (900, 4, 10, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (901, 4, 11, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (902, 4, 12, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (903, 4, 13, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (904, 4, 14, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (905, 4, 15, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (906, 4, 16, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (907, 4, 17, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (908, 4, 18, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (909, 4, 19, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (910, 4, 20, 'A303');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (911, 1, 1, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (912, 1, 2, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (913, 1, 3, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (914, 1, 4, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (915, 1, 5, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (916, 1, 6, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (917, 1, 7, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (918, 1, 8, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (919, 1, 9, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (920, 1, 10, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (921, 1, 11, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (922, 1, 12, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (923, 1, 13, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (924, 1, 14, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (925, 1, 15, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (926, 1, 16, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (927, 1, 17, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (928, 1, 18, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (929, 1, 19, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (930, 1, 20, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (931, 2, 1, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (932, 2, 2, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (933, 2, 3, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (934, 2, 4, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (935, 2, 5, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (936, 2, 6, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (937, 2, 7, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (938, 2, 8, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (939, 2, 9, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (940, 2, 10, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (941, 2, 11, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (942, 2, 12, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (943, 2, 13, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (944, 2, 14, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (945, 2, 15, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (946, 2, 16, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (947, 2, 17, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (948, 2, 18, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (949, 2, 19, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (950, 2, 20, 'SE02');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (951, 1, 1, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (952, 1, 2, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (953, 1, 3, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (954, 1, 4, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (955, 1, 5, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (956, 1, 6, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (957, 1, 7, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (958, 1, 8, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (959, 1, 9, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (960, 1, 10, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (961, 1, 11, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (962, 1, 12, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (963, 1, 13, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (964, 1, 14, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (965, 1, 15, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (966, 1, 16, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (967, 1, 17, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (968, 1, 18, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (969, 1, 19, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (970, 1, 20, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (971, 2, 1, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (972, 2, 2, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (973, 2, 3, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (974, 2, 4, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (975, 2, 5, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (976, 2, 6, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (977, 2, 7, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (978, 2, 8, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (979, 2, 9, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (980, 2, 10, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (981, 2, 11, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (982, 2, 12, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (983, 2, 13, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (984, 2, 14, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (985, 2, 15, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (986, 2, 16, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (987, 2, 17, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (988, 2, 18, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (989, 2, 19, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (990, 2, 20, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (991, 3, 1, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (992, 3, 2, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (993, 3, 3, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (994, 3, 4, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (995, 3, 5, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (996, 3, 6, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (997, 3, 7, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (998, 3, 8, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (999, 3, 9, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1000, 3, 10, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1001, 3, 11, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1002, 3, 12, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1003, 3, 13, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1004, 3, 14, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1005, 3, 15, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1006, 3, 16, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1007, 3, 17, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1008, 3, 18, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1009, 3, 19, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1010, 3, 20, 'TT30');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1064, 1, 1, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1065, 1, 2, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1066, 1, 3, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1067, 1, 4, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1068, 1, 5, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1069, 1, 6, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1070, 1, 7, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1071, 1, 8, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1072, 1, 9, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1073, 1, 10, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1074, 1, 11, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1075, 1, 12, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1076, 1, 13, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1077, 1, 14, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1078, 1, 15, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1079, 1, 16, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1080, 1, 17, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1081, 1, 18, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1082, 1, 19, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1083, 1, 20, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1084, 2, 1, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1085, 2, 2, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1086, 2, 3, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1087, 2, 4, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1088, 2, 5, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1089, 2, 6, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1090, 2, 7, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1091, 2, 8, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1092, 2, 9, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1093, 2, 10, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1094, 2, 11, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1095, 2, 12, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1096, 2, 13, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1097, 2, 14, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1098, 2, 15, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1099, 2, 16, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1100, 2, 17, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1101, 2, 18, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1102, 2, 19, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1103, 2, 20, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1104, 3, 1, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1105, 3, 2, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1106, 3, 3, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1107, 3, 4, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1108, 3, 5, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1109, 3, 6, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1110, 3, 7, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1111, 3, 8, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1112, 3, 9, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1113, 3, 10, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1114, 3, 11, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1115, 3, 12, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1116, 3, 13, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1117, 3, 14, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1118, 3, 15, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1119, 3, 16, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1120, 3, 17, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1121, 3, 18, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1122, 3, 19, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1123, 3, 20, 'B18');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1124, 1, 1, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1125, 1, 2, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1126, 1, 3, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1127, 1, 4, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1128, 1, 5, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1129, 1, 6, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1130, 1, 7, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1131, 1, 8, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1132, 1, 9, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1133, 1, 10, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1134, 1, 11, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1135, 1, 12, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1136, 1, 13, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1137, 1, 14, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1138, 1, 15, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1139, 1, 16, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1140, 1, 17, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1141, 1, 18, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1142, 1, 19, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1143, 1, 20, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1144, 2, 1, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1145, 2, 2, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1146, 2, 3, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1147, 2, 4, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1148, 2, 5, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1149, 2, 6, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1150, 2, 7, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1151, 2, 8, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1152, 2, 9, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1153, 2, 10, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1154, 2, 11, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1155, 2, 12, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1156, 2, 13, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1157, 2, 14, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1158, 2, 15, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1159, 2, 16, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1160, 2, 17, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1161, 2, 18, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1162, 2, 19, 'O34');
INSERT INTO public.seats (id, cabine, number, train_id) VALUES (1163, 2, 20, 'O34');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1011, '2017-05-11 21:00:00', '2017-05-11 10:00:00', 10019, 194, 'F01');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1167, '2017-06-02 06:00:00', '2017-06-01 04:00:00', 10019, 130, 'SE02');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1057, '2017-04-30 23:00:00', '2017-04-29 22:30:00', 10024, 10002, 'A303');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1059, '2017-06-01 06:00:00', '2017-06-01 02:00:00', 130, 361, 'TT30');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1060, '2017-06-02 17:00:00', '2017-06-01 22:00:00', 10019, 130, 'F01');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1015, '2017-05-21 07:00:00', '2017-05-20 21:00:00', 1014, 361, 'SE02');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1164, '2017-06-02 02:00:00', '2017-06-01 18:00:00', 1014, 361, 'B18');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1166, '2017-06-03 10:00:00', '2017-06-02 06:00:00', 10019, 1014, 'A303');
INSERT INTO public.schedules (id, time_arrival, time_departure, station_arrival_id, station_departure_id, train_id) VALUES (1165, '2017-06-03 12:00:00', '2017-06-02 04:00:00', 10019, 1014, 'O34');
INSERT INTO public.rides (id, time_arrival, time_departure, seat_id, station_arrival_id, station_departure_id, ticket_id, train_id) VALUES (1013, '2017-05-11 21:00:00', '2017-05-11 10:00:00', 756, 10019, 194, 1012, 'F01');
INSERT INTO public.rides (id, time_arrival, time_departure, seat_id, station_arrival_id, station_departure_id, ticket_id, train_id) VALUES (1020, '2017-05-21 08:00:00', '2017-05-20 22:00:00', 936, 1014, 361, 1019, 'SE02');
INSERT INTO public.tickets (id, user_id) VALUES (1012, 129);
INSERT INTO public.tickets (id, user_id) VALUES (1019, 129);
